Repository skill-trees/Algorithm, pull requests merged in 2023-05, with the labels that each got.

#156 [중현] 0501 두 용액
  18주차/0501/두용액_joong2043.java
Labels: ✅ 한번에 성공

#157 [중현] 0504 휴게소 세우기
  18주차/0504/휴게소세우기_joong2043.java
Labels: 👍 재시도 성공 👍

#160 [sandbend] 두용액 휴게소세우기
  18주차/0501/두용액_sandbend.java
  18주차/0504/휴게소세우기_sandbend.java
Labels: 👍 재시도 성공 👍

#165 [ur2e] 18주차
  18주차/0501/두용액_ur2e.java
  18주차/0504/휴게소세우기_ur2e.java
  18주차/0505/숨바꼭질_ur2e.java
Labels: 👍 재시도 성공 👍

#167 [중현] 0512 경쟁적 전염
  19주차/0512/경쟁적전염_joong2043.java
Labels: ✅ 한번에 성공

#169 [hellojihyoung] 행성터널
  19주차/0508/행성터널_hellojihyoung.py
Labels: 🚨 다시보기

#171 [중현] 0508 행성 터널
  19주차/0508/행성터널_joong2043.java
Labels: 👍 재시도 성공 👍

#172 [sandbend] 사과나무
  19주차/0509/사과나무_sandbend.java
Labels: 👍 재시도 성공 👍

#177 [sandbend] 공유기설치
  20주차/0516/공유기설치_sandbend.java
Labels: 👍 재시도 성공 👍

#179 [중현] 떡먹는 호랑이
  20주차/0519/떡먹는호랑이_joong2043.java
Labels: 👍 재시도 성공 👍

#181 [sandbend] 떡먹는호랑이
  20주차/0519/떡먹는호랑이_sandbend.java
Labels: 🚨 다시보기

#186 [중현] 알파벳
  21주차/0525/알파벳_joong2043.java
Labels: ✅ 한번에 성공

#189 [rlarltj] 21주차
  21주차/0525/알파벳_rlarltj.java
  21주차/0526/센서_rlarltj.java
Labels: ✅ 한번에 성공

#191 [sandbend] 참외밭 알파벳 센서
  21주차/0523/참외밭_sandbend.java
  21주차/0525/알파벳_sandbned.java
  21주차/0526/센서_sandbend.java
Labels: 👍 재시도 성공 👍

#193 [yerim] 알파벳, 센서
  21주차/0525/알파벳_yerim.java
  21주차/0526/센서_yerim.java
Labels: ✅ 한번에 성공

#187 [황종욱] 21주차
  21주차/0525/알파벳_jongwuk/Main.java
  21주차/0525/팰린드롬만들기_jongwuk/Main.java
Labels: 🚨 다시보기
