Repository skill-trees/Algorithm, pull requests merged in 2023-04, with the labels that each got.

#108 [sandbend] 큰수의법칙 럭키스트레이트
  13주차/0327/큰수의법칙_sandbend.java
  13주차/0328/럭키스트레이트_sandbend.java
Labels: ✅ 한번에 성공

#107 [중현] 0330 음료수 얼려먹기 & 연구소 || 0331 카드 정렬하기
  13주차/0330/연구소_joong2043.java
  13주차/0330/음료수얼려먹기_joong2043.java
  13주차/0331/카드정렬하기_joong2043.java
Labels: ✅ 한번에 성공

#111 [sandbend] 위에서아래로
  13주차/0331/위에서아래로_sandbend.java
Labels: ✅ 한번에 성공

#112 [2214yj] 13주차 알고리즘
  13주차/0328/럭키스트레이트_2214yj.java
  13주차/0328/왕실의나이트_2214yj.java
  13주차/0330/음료수얼려먹기_2214yj.java
  13주차/0331/위에서아래로_2214yj.java
  13주차/0331/카드정렬하기_2214yj.java
Labels: ✅ 한번에 성공, 👍 재시도 성공 👍, 🚨 다시보기

#113 [중현] 0403 정렬된 배열에서 특정 수의 개수 구하기 / 0404 병사배치하기
  14주차/0403/정렬된배열에서특정수의개수구하기_joong2043.java
  14주차/0404/병사 배치하기_joong2043.java
Labels: ✅ 한번에 성공

#114 [hellojihyoung] 병사 배치하기
  14주차/0404/병사 배치하기_hellojihyoung.py
Labels: ✅ 한번에 성공

#115 [중현] 0404 병사 배치하기
  14주차/0404/병사 배치하기_joong2043.java
Labels: ✅ 한번에 성공

#116 [hellojihyoung] 정렬된 배열에서 특정 수의 개수 구하기
  14주차/0403/정렬된 배열에서 특정 수의 개수 구하기_hellojihyoung.py
Labels: ✅ 한번에 성공

#117 [sandbend] 정렬된 배열에서 특정수의 개수 구하기
  14주차/0403/정렬된배열에서특정수의개수구하기_sandbend.java
Labels: 👍 재시도 성공 👍

#118 [중현] 0407 여행 계획
  14주차/0407/여행계획_joong2043.java
Labels: ✅ 한번에 성공

#119 [sandbend] 여행계획
  14주차/0407/여행계획_sandbend.java
Labels: 🚨 다시보기

#123 [sandbend] 미래도시
  14주차/0406/미래도시_sandbend.java
Labels: 🚨 다시보기

#121 [ur2e] 14주차 0403 & 0404 & 0406 & 0407
  14주차/0403/정렬된배열에서특정수의개수구하기_ur2e.java
  14주차/0404/병사배치하기_ur2e.java
  14주차/0406/미래도시_ur2e.java
  14주차/0407/여행계획_ur2e.java
Labels: ✅ 한번에 성공, 👍 재시도 성공 👍, 🚨 다시보기

#125 [ur2e] 어두운 길
  15주차/0410/어두운길_ur2e.java
Labels: ✅ 한번에 성공

#126 [ur2e] 0411 신입사원
  15주차/0411/신입사원_ur2e.java
Labels: 👍 재시도 성공 👍

#127 [중현] 0410 어두운 길 & 0411 신입사원
  14주차/0407/여행계획_joong2043.java
  15주차/0410/어두운길_joong2043.java
  15주차/0411/신입사원_joong2043.java
Labels: ✅ 한번에 성공

#128 [sandbend] 어두운길
  15주차/0410/어두운길_sandbend.java
Labels: 🚨 다시보기

#129 [sandbend] 신입사원
  15주차/0411/신입사원_sandbend.java
Labels: 👍 재시도 성공 👍

#132 [2214yj] 15주차 알고리즘
  15주차/0411/신입사원_2214yj.java
  15주차/0414/스타트링크_2214yj.java
  DFS_알고리즘/N과 M 수열구하기/N과 M 수열구하기_2214yj.java
Labels: ✅ 한번에 성공, 👍 재시도 성공 👍

#133 15주차 0413-0414
  15주차/0413/문자열압축_ur2e.java
  15주차/0414/스타트링크_ur2e.java
Labels: ✅ 한번에 성공, 👍 재시도 성공 👍

#136 [ur2e] 16주차
  16주차/0417/숫자정사각형_ur2e.java
  16주차/0417/좌표압축_ur2e.java
Labels: 👍 재시도 성공 👍

#137 [sandbend] 좌표압축
  16주차/0417/좌표압축_sandbend.java
Labels: 👍 재시도 성공 👍

#138 [중현] 0420 가장 긴 증가하는 부분 수열 & 0421 정확한 순위
  16주차/0420/가장긴증가하는부분수열_joong2043.java
  16주차/0421/정확한순위_joong2043.java
Labels: ✅ 한번에 성공

#139 [중현] 0418 가장 긴 증가하는 부분 수열3
  16주차/0418/가장긴증가하는부분수열3_joong2043.java
  16주차/0420/가장긴증가하는부분수열_joong2043.java
Labels: 👍 재시도 성공 👍

#141 [sandbend] 가장긴증가하는부분수열3
  16주차/0418/가장긴증가하는부분수열3_sandbend.java
Labels: 🚨 다시보기

#145 [ur2e] 16주차
  16주차/0418/가장긴증가하는부분수열3_ur2e.java
  16주차/0420/가장긴증가하는부분수열_ur2e.java
  16주차/0421/정확한순위_ur2e.java
Labels: ✅ 한번에 성공, 👍 재시도 성공 👍

#147 [sandbend] 여행계획
  17주차/0424/여행계획_sandbend.java
Labels: 👍 재시도 성공 👍

#148 [중현] 0428 인구 이동
  17주차/0428/인구이동_joong2043.java
Labels: 👍 재시도 성공 👍

#149 [sandbend] 강의실배정
  17주차/0425/강의실배정_sandbend.java
Labels: 👍 재시도 성공 👍

#152 [중현] 회의실 배정
  17주차/0427/회의실배정_joong2043.java
Labels: 👍 재시도 성공 👍
